triggers:
  - github-pull-request:
    build-desc-template: "${build-desc-template}"
    trigger-phrase: 'retest this please'
    only-trigger-phrase: false
    github-hooks: true
    permit-all: true
    auto-close-on-fail: false

