version = 1

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "node_modules/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "tests/.mypy**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "tests/__pycache__/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "relnotes/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "releasenotes/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "jjb/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = ".jjb-test/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "docs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "jenkins-admin/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "schema/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"

[[annotations]]
path = "reusable-tox-run-action/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Linux Foundation"
SPDX-License-Identifier = "EPL-1.0"
